- aleo.abnf
The previous version
```
identifier = 1*letter *( letter / ... )
```
is purposely derived from the nom parser, which uses `alpha1` (i.e. one or more ASCII alphabetical characters) for `1*letter` above.
However, the rule is technically ambiguous, because there may be multiple ways to divide the initial letters of an identifier betweeen the `1*letter` part and the `*( letter / ... )` part (e.g. `abc` can be organized either as `a` then `bc` or as `ab` then `c`).
There is nothing wrong in the nom parser, which disambiguates the situation by parsing as many letters as possible via `alpha1`, which is a form of extra-grammatical disambiguation.
While we could disambiguate the ABNF grammar rule via an extra-grammatical predicate, it is simpler to make the rule non-ambiguous (also for formal …
> [Aleo] Tweak rule for identifiers.

- aleo.abnf
This does not change the language defined by the grammar. It only optimizes a few rules to avoid an extra group layer `( ... )`, which is presumably a leftover from a time in which it was preceded by some whitespace and/or comments. The presence or absence of the layer are equivalent for most purposes, but they lead to slightly different CSTs.
> [Aleo] Remove a layer in the grammar formulation.

- leo.abnf
The unit type is considered a primitive type, since its (only) value is atomic, i.e. does not consist of aggregated sub-values. However, it is not a named type, because it is denoted via the symbols `(` `)` and not via an identifier or a keyword. These distinctions are reflected in the modified rules, which are more than just addint a unit type.
The unit expression is added as a primary expression.
Note that there may be whitespace and comments between the opening and closing parentheses of the unit type or expression. Even though it would be generally a discouraged practice to actually put whitespace and comments there, it seems appropriate to allow that at the grammar level. If we wanted to disallow that, we would have to add `()` as a new symbol lexeme.
Partially related to the …
> [Leo] Add the unit type and expression.

- leo.abnf
Besides a single identifier, a variable or constant declaration can now have a tuple of two or more identifiers.
> [Leo] Allow tuples in declarations.

- leo.abnf
This is consistent with the Leo parser implementation.
> [Leo] Make return expression optional.

- leo.abnf
This is allowed in function parameters and output types of transition functions and finalizer functions (not helper functions). The grammar captures the restriction on helper function's output types, but not on helper function's parameters. It could, if we differentiated the function parameters, but it may not be worth the complication.
> [Leo] Add the `private` modifier.

- leo.abnf
The `finalize` statement is removed, along with the `async` keyword, and merged into the `return` statement, where the expression may now be optionally followed by `then finalize(...)`, with `then` a new keyword.
> [Leo] Merge `finalize` into `return`.

- leo.abnf
> [Leo] Make transition output type optional.

- aleo.abnf
- leo.abnf
Add references to ABNF notation.
Specify that the grammar applies to UTF-8-decoded files.
Closes #4.
> [Leo] [Aleo] Expand doc.

- leo.abnf
As discussed/confirmed, the modes are only `private`, `public`, and `constant`.
The keyword `const` is retained because it is still used to declare constants (while `let` is used for variables).
We can merge this later, when we make the corresponding change to the Leo compiler.
> [Leo] Remove the `const` mode.

- leo.abnf
This was an oversight in the grammar, which this PR fixes.
> [Leo] Make `inline` output type optional.

- aleo.abnf
Since currently snarkVM still uses 'functions' and 'closures', we align the grammar with that. This may change in the future.
> [Aleo instructions] Revert function nomenclature.

- aleo.abnf
Function calls no longer have to have operands.
> [Aleo] Make operands optional for `call`

- leo.abnf
The keywords `assert`, `assert_eq` and `assert_neq` is defined as keywords in Leo compiler, but not in the grammar definition.
> [Leo] Add assert function names as keywords

- aleo.abnf
Also removes hexadecimal digits, which are currently only used in string literals.
This aligns the grammar with the current implementation.
> [Aleo instructions] Remove string literals.

- aleo.abnf
This matches https://github.com/AleoHQ/snarkVM/pull/1576.
As always, the updated grammar has been run through the ACL2 verified ABNF grammar parser, and some properties of the grammar (such as well-formedness and closure) have been proved in ACL2 (automatically).
> [Aleo instructions] Add hash and commit ops.

- aleo.abnf
This is added to the `operand` rule (which is also now split across multiple lines), instead of the `literal` rule, to follow more closely the snarkVM parser implementation, which handles this new operand in the parser for operands, not the parser for literals.
This concerns the concrete syntax of Aleo instructions. The snarkVM parser actually turns `group::GEN` into a literal in the abstract syntax. This makes the (implicit) syntax abstraction mapping dependent on the curve used.
Matches https://github.com/AleoHQ/snarkVM/pull/1594.
> [Aleo ins.] Add `group::GEN` operand.

- leo.abnf
This is split into three commits which may be easier to review:
1. Remove the special increment and decrement statements.
2. Rename 'static functions' to 'associated functions'.
3. Generalize 'operator calls' to 'method calls'.
This covers the updates for the mapping ops (probably just the 1st one suffices for that), but the other two make the grammar consistent with the current language in additional dimensions.
> [Leo] Update mapping ops and generalize methods

- aleo.abnf
The second commit builds on top of the first, which renamed `get.or_init` to `get.or_use`; the PR with that commit will be closed, as it's superseded by this one. The second commit adds the mapping commands `contains` and `remove`, and the `rand.chacha` commands.
> Updates form mapping and random commands.

- leo.abnf
These are primary expressions, with comments and whitespace allowed between the two words and the dot.
This also adds `self` and `block` to the keywords, which therefore cannot be used as identifiers.
> [Leo] Add `self.caller` and `block.height`.

- aleo.abnf
Matches:
- https://github.com/AleoHQ/snarkVM/pull/1673
- https://github.com/AleoHQ/snarkVM/pull/1665
The snarkVM use 'cast type' for the thing that is either a register type or `group.x` or `group.y`. In the grammar I use `cast-destination` instead, because `group.x` and `group.y` are not quite types.
> [Aleo ins.] Update cast instructions.

- aleo.abnf
This brings in the `branch` and `position` commands, whose PR was made to staging. But since they are already in snarkVM's testnet3, it's appropriate for this grammar extension to be in master in this repo.
> Merge staging into master

- leo.abnf
As detailed in [Leo PR](https://github.com/AleoHQ/leo/issues/2538) want to allow numbers like `1_000_000u32` to exist. This is similar to the [Aleo grammar](https://github.com/AleoHQ/grammars/blob/1e3c08275395f1afb733dde78aaddd727eeebbcd/aleo.abnf#L177C1-L177C1) and [Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=554372f372214b10c2d4bc8783d194c0).
> [Leo] Add support for underscores in numeric literals

- aleo.abnf
Closes #53, #54, #55, #56, #57, #58, #59, #60, #61.
> [Aleo ins] Update grammar based on audit.

- aleo.abnf
- Remove key and value identifiers in mapping declarations.
- Add an explicit type for mapping keys and values.
- Remove the `finalize` command.
- Add `async` instruction.
- Extend types of cast destinations.
- Generalize many `into` destinations to register access (not just register).
- Inline some `...-op` rules with just one alternative.
- Add the `await` command.
- Add `self.signer`.
- Remove string type.
- Add `<locator>.future` to finalize types, value types, and register types.
- Add `cast.lossy`.
Based on https://github.com/AleoHQ/snarkVM/pull/1994, https://github.com/AleoHQ/snarkVM/pull/2009, https://github.com/AleoHQ/snarkVM/pull/2015, https://github.com/AleoHQ/snarkVM/pull/2020.
> [Aleo ins] Update to latest snarkVM.

- aleo.abnf
Remove the `cws` that was preceding `array-type`.
Matches https://github.com/AleoHQ/snarkVM/pull/2056.
> [Aleo ins] Remove anomaly with array types.

- leo.abnf
This passes all the usual ACL2 checks.
> [Leo] Add hexadecimal, octal, binary numerals.

- leo.abnf
Matches https://github.com/ProvableHQ/leo/pull/28492.
> [Leo] Remove affine group literals.
